# Parte 3 — Clientes e Pagamentos

In [4]:
%run ../src/librarys.ipynb

## 1. Carregamento dos dados

In [5]:
data = ["order_purchase_timestamp", "order_approved_at",
         "order_delivered_carrier_date", "order_delivered_customer_date",
         "order_estimated_delivery_date"]
orders = pd.read_csv("../data/processed/orders_enriched.csv", parse_dates=data)
customers = pd.read_csv("../data/processed/customers.csv")

In [6]:
orders.shape

(99441, 17)

In [7]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
order_price                             float64
order_freight                           float64
order_total                             float64
review_score                            float64
customer_state                              str
customer_city                               str
purchase_year_month                         str
dt_diff                                 float64
is_late                                 float64
dtype: object

In [8]:
customers.shape

(99441, 5)

In [9]:
print(orders.shape)
print(customers.shape)

(99441, 17)
(99441, 5)

## 2. Junção com clientes

In [10]:
tabela_base = pd.merge(orders, customers[['customer_id', 'customer_unique_id']], on='customer_id', how='left')

In [11]:
tabela_base.shape

(99441, 18)

In [12]:
tabela_base["customer_unique_id"].isna().sum()

np.int64(0)

In [13]:
tabela_base['order_status'] == 'DELIVERED'

0        True
1        True
2        True
3        True
4        True
         ...
99436    True
99437    True
99438    True
99439    True
99440    True
Name: order_status, Length: 99441, dtype: bool

In [14]:
tabela_base[tabela_base['order_status'] == 'DELIVERED']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_price,order_freight,order_total,review_score,customer_state,customer_city,purchase_year_month,dt_diff,is_late,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,DELIVERED,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,38.71,4.0,SP,SAO PAULO,2017-10,-8.0,0.0,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,DELIVERED,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,141.46,4.0,BA,BARREIRAS,2018-07,-6.0,0.0,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,DELIVERED,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,179.12,5.0,GO,VIANOPOLIS,2018-08,-18.0,0.0,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,DELIVERED,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,72.20,5.0,RN,SAO GONCALO DO AMARANTE,2017-11,-13.0,0.0,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,DELIVERED,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,28.62,5.0,SP,SANTO ANDRE,2018-02,-10.0,0.0,72632f0f9dd73dfee390c9b22eb56dd6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,DELIVERED,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,72.00,13.08,85.08,5.0,SP,SAO JOSE DOS CAMPOS,2017-03,-11.0,0.0,6359f309b166b0196dbf7ad2ac62bb5a
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,DELIVERED,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,174.90,20.10,195.00,4.0,SP,PRAIA GRANDE,2018-02,-2.0,0.0,da62f9e57a76d978d02ab5362c509660
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,DELIVERED,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,205.99,65.02,271.01,5.0,BA,NOVA VICOSA,2017-08,-6.0,0.0,737520a9aad80b3fbbdad19b66b37b30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,DELIVERED,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,359.98,81.18,441.16,2.0,RJ,JAPUIBA,2018-01,-21.0,0.0,5097a5312c8b157bb7be58ae360ef43c
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,DELIVERED,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,68.50,18.36,86.86,5.0,PR,LAPA,2018-03,-18.0,0.0,60350aa974b26ff12caad89e55993bd6

In [15]:
tabela_base[(tabela_base["order_status"] == "DELIVERED") & (tabela_base['purchase_year_month']>='2017-01') & (tabela_base['purchase_year_month']<='2018-08')]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_price,order_freight,order_total,review_score,customer_state,customer_city,purchase_year_month,dt_diff,is_late,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,DELIVERED,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,38.71,4.0,SP,SAO PAULO,2017-10,-8.0,0.0,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,DELIVERED,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,141.46,4.0,BA,BARREIRAS,2018-07,-6.0,0.0,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,DELIVERED,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,179.12,5.0,GO,VIANOPOLIS,2018-08,-18.0,0.0,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,DELIVERED,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,72.20,5.0,RN,SAO GONCALO DO AMARANTE,2017-11,-13.0,0.0,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,DELIVERED,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,28.62,5.0,SP,SANTO ANDRE,2018-02,-10.0,0.0,72632f0f9dd73dfee390c9b22eb56dd6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,DELIVERED,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,72.00,13.08,85.08,5.0,SP,SAO JOSE DOS CAMPOS,2017-03,-11.0,0.0,6359f309b166b0196dbf7ad2ac62bb5a
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,DELIVERED,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,174.90,20.10,195.00,4.0,SP,PRAIA GRANDE,2018-02,-2.0,0.0,da62f9e57a76d978d02ab5362c509660
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,DELIVERED,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,205.99,65.02,271.01,5.0,BA,NOVA VICOSA,2017-08,-6.0,0.0,737520a9aad80b3fbbdad19b66b37b30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,DELIVERED,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,359.98,81.18,441.16,2.0,RJ,JAPUIBA,2018-01,-21.0,0.0,5097a5312c8b157bb7be58ae360ef43c
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,DELIVERED,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,68.50,18.36,86.86,5.0,PR,LAPA,2018-03,-18.0,0.0,60350aa974b26ff12caad89e55993bd6

## 3. Filtros do projeto
Apenas pedidos DELIVERED entre jan/2017 e ago/2018, conforme as regras do projeto. Validação: receita total de R$ 15.373.120,01, igual às tabelas agregadas." E, na seção 4: "Apenas 3,0% dos clientes compraram mais de uma vez.

In [16]:
base_filtrada = tabela_base[(tabela_base["order_status"] == "DELIVERED") & (tabela_base['purchase_year_month']>='2017-01') & (tabela_base['purchase_year_month']<='2018-08')]

In [17]:
base_filtrada.shape

(96211, 18)

In [18]:
base_filtrada['order_total'].sum()

np.float64(15373120.01)

## 4. Visão por cliente

In [19]:
clientes = base_filtrada.groupby("customer_unique_id").agg(
    pedidos=("order_id", "nunique"),
    valor_total=("order_total", "sum"),
    ultima_compra=("order_purchase_timestamp", "max")
)

In [29]:
clientes.head()

                                  pedidos  valor_total       ultima_compra
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2        1       141.90 2018-05-10 10:56:27
0000b849f77a49e4a4ce2b2a4ca5be3f        1        27.19 2018-05-07 11:11:27
0000f46a3911fa3c0805444483337064        1        86.22 2017-03-10 21:05:03
0000f6ccb0745a6a4b88665a16c9f078        1        43.62 2017-10-12 20:29:41
0004aac84e0df4da2b147fca70cf8255        1       196.89 2017-11-14 19:45:42

In [20]:
clientes.shape

(93104, 3)

In [21]:
clientes['valor_total'].sum()

np.float64(15373120.010000002)

In [22]:
clientes["pedidos"] > 1

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    False
0000b849f77a49e4a4ce2b2a4ca5be3f    False
0000f46a3911fa3c0805444483337064    False
0000f6ccb0745a6a4b88665a16c9f078    False
0004aac84e0df4da2b147fca70cf8255    False
                                    ...
fffcf5a5ff07b0908bd4e2dbc735a684    False
fffea47cd6d3cc0a88bd621562a9d061    False
ffff371b4d645b6ecea244b27531430a    False
ffff5962728ec6157033ef9805bacc48    False
ffffd2657e2aad2907e67c3e9daecbeb    False
Name: pedidos, Length: 93104, dtype: bool

In [23]:
recorrentes = clientes[clientes["pedidos"] > 1]

In [24]:
len(recorrentes)

2789

In [25]:
len(recorrentes) / len(clientes) * 100

2.995574841037979

In [26]:
round(len(recorrentes) / len(clientes) * 100,1)

3.0

## RFM - Recência

### 5.1 Recência

In [31]:
data_ref = base_filtrada["order_purchase_timestamp"].max()

In [32]:
print(data_ref)

2018-08-29 15:00:37

In [35]:
clientes['recencia'] = (data_ref - clientes['ultima_compra']).dt.days
clientes['recencia'].describe()

count    93104.000000
mean       235.702924
std        150.942219
min          0.000000
25%        113.000000
50%        217.000000
75%        344.000000
max        601.000000
Name: recencia, dtype: float64